// Каталог испытательных сценариев стенда.
// Это реальный протокол регресса: каждый сценарий можно прогнать с сайта,
// ожидание проверяется программно (src/verify.js), вердикт пишется в БД.

export const SCENARIOS = [
  // ---------- smart home ----------
  {
    id: 'sh-lights-level',
    group: 'smart_home',
    title: 'Уровень яркости без глагола',
    prompt: 'set the bedroom lights to 40 percent',
    mode: 'tools',
    toolset: 'smart_home',
    expect: { calls: [{ name: 'set_lights', args: { room: 'bedroom', action: 'on', brightness: 40 } }] },
    note: 'В запросе нет «on/off» — включение выводится из факта установки уровня. Раньше поле-булево ошибочно получало false.',
  },
  {
    id: 'sh-lights-off',
    group: 'smart_home',
    title: 'Выключение без лишних полей',
    prompt: 'turn off the living room lights',
    mode: 'tools',
    toolset: 'smart_home',
    expect: { calls: [{ name: 'set_lights', args: { room: 'living room', action: 'off' } }] },
    note: 'Строгая проверка: brightness в запросе не назван — выдуманное значение считается ошибкой.',
  },
  {
    id: 'sh-lights-dim',
    group: 'smart_home',
    title: '«Приглушить» как включение',
    prompt: 'dim the kitchen to 20',
    mode: 'tools',
    toolset: 'smart_home',
    expect: { calls: [{ name: 'set_lights', args: { room: 'kitchen', action: 'on', brightness: 20 } }] },
    note: 'Dim = включить с низким уровнем.',
  },
  {
    id: 'sh-thermo-warm',
    group: 'smart_home',
    title: 'Термостат: «warm up»',
    prompt: "it's freezing in here, warm the place up to 24 degrees",
    mode: 'tools',
    toolset: 'smart_home',
    expect: { calls: [{ name: 'set_thermostat', args: { temperature: 24, mode: 'warm' } }] },
    note: 'Ранее модель уверенно ставила mode=cool на любой запрос нагрева; исправлено совпадением значений enum со словами пользователя.',
  },
  {
    id: 'sh-thermo-cool',
    group: 'smart_home',
    title: 'Термостат: охлаждение',
    prompt: 'cool the place down to 20 degrees',
    mode: 'tools',
    toolset: 'smart_home',
    expect: { calls: [{ name: 'set_thermostat', args: { temperature: 20, mode: 'cool' } }] },
    note: "Зеркальный контроль к sh-thermo-warm. Косвенные формулировки («it's hot») в значение enum не маппируются моделью — известное ограничение, зафиксировано в отчёте итерации 2.",
  },
  {
    id: 'sh-multi',
    group: 'smart_home',
    title: 'Две команды в одном запросе',
    prompt: 'lock the front door and start cleaning the kitchen',
    mode: 'tools',
    toolset: 'smart_home',
    expect: {
      calls: [
        { name: 'lock_door', args: { door: 'front door', lock: true } },
        { name: 'start_cleaning', args: { room: 'kitchen' } },
      ],
    },
    note: 'Порядок вызовов должен соответствовать порядку команд.',
  },
  {
    id: 'sh-refuse-weather',
    group: 'smart_home',
    title: 'Отказ: инструмента нет',
    prompt: "what's the weather in Paris tomorrow?",
    mode: 'tools',
    toolset: 'smart_home',
    expect: { refusal: true },
    note: 'Погодного инструмента нет — ожидается пустой список вызовов, не догадка.',
  },
  {
    id: 'sh-refuse-joke',
    group: 'smart_home',
    title: 'Отказ: внесистемный запрос',
    prompt: 'tell me a joke',
    mode: 'tools',
    toolset: 'smart_home',
    expect: { refusal: true },
    note: 'Известная проблема: модель вместо отказа вызывает start_cleaning с пустой комнатой. Открытый кейс.',
  },

  // ---------- media player ----------
  {
    id: 'mp-play',
    group: 'media_player',
    title: 'Воспроизведение по жанру',
    prompt: 'play some jazz',
    mode: 'tools',
    toolset: 'media_player',
    expect: { calls: [{ name: 'play_media' }] },
    note: 'Проверяется выбор инструмента и наличие title; точная формулировка жанра не фиксируется.',
  },
  {
    id: 'mp-volume-relative',
    group: 'media_player',
    title: 'Удержание выдуманного аргумента',
    prompt: "turn the volume down, it's too loud",
    mode: 'tools',
    toolset: 'media_player',
    expect: { suppressed: true },
    note: 'Уровень в запросе не назван; вызов с выдуманным уровнем должен быть удержан (suppressed_calls), а не исполнен.',
  },

  // ---------- productivity ----------
  {
    id: 'pr-meeting-rel',
    group: 'productivity',
    title: 'Относительная дата «tomorrow»',
    prompt: 'schedule a standup with the team tomorrow at 9',
    mode: 'tools',
    toolset: 'productivity',
    system_facts: 'date: 2026-09-26 Sat 14:00',
    expect: { calls: [{ name: 'schedule_meeting', argsContains: { date: '2026-09-27', time: '09:00' } }] },
    note: 'Разрешение относительной даты только при наличии факта date. Ранее сценарий обрывался по бюджету токенов (ключ format в схеме ломал грамматику).',
  },
  {
    id: 'pr-task',
    group: 'productivity',
    title: 'Задача с датой',
    prompt: 'create a task "Verify emails from John" on tomorrow',
    mode: 'tools',
    toolset: 'productivity',
    system_facts: 'date: 2026-09-26 Sat 14:00',
    expect: { calls: [{ name: 'create_task', args: { title: 'Verify emails from John', due_date: '2026-09-27' } }] },
    note: 'Цитата копируется дословно в title.',
  },

  // ---------- messaging ----------
  {
    id: 'ms-money-slang',
    group: 'messaging',
    title: 'Число прописью',
    prompt: 'send @maria twenty bucks',
    mode: 'tools',
    toolset: 'messaging',
    expect: { calls: [{ name: 'send_money', args: { amount: 20, to: 'maria' } }] },
    note: 'twenty → 20, префикс @ отбрасывается.',
  },
  {
    id: 'ms-money-limit',
    group: 'messaging',
    title: 'Сумма вне лимита инструмента',
    prompt: 'send $15000 to @bob right now',
    mode: 'tools',
    toolset: 'messaging',
    expect: { calls: [{ name: 'send_money', args: { amount: 15000, to: 'bob' } }] },
    note: 'Ограничение maximum убрано из схемы: раньше значение вне лимита молча искажалось (15000 → 1500). Теперь лимит применяется на стороне системы, а не грамматики.',
  },
  {
    id: 'ms-ride',
    group: 'messaging',
    title: 'Маршрут «from X to Y»',
    prompt: 'get me a taxi from the office to the airport, comfort class',
    mode: 'tools',
    toolset: 'messaging',
    expect: { calls: [{ name: 'book_ride', args: { pickup: 'office', destination: 'airport', ride_type: 'comfort' } }] },
    note: 'Поля pickup/destination читаются из конструкции from…to….',
  },

  // ---------- extraction ----------
  {
    id: 'ex-invoice',
    group: 'invoice',
    title: 'Счёт с позициями',
    prompt: 'Vendor: Blackwell Supplies Ltd. Invoice number: BS-2026-0417. Issued on January 12, 2026, payment due February 11, 2026. Items: 3 office chairs at $89.90 each, 2 desks at $210.00 each, delivery fee $25.00. Total amount due: $514.70 USD. Please transfer the funds to our account.',
    mode: 'extract',
    schema_name: 'invoice',
    expect: {
      record: {
        vendor: 'Blackwell Supplies Ltd.',
        invoice_number: 'BS-2026-0417',
        issue_date: '2026-01-12',
        due_date: '2026-02-11',
        total: 514.7,
        currency: 'USD',
        items: [
          { description: 'office chairs', quantity: 3, unit_price: 89.9 },
          { description: 'desks', quantity: 2, unit_price: 210 },
          { description: 'delivery fee', quantity: 1, unit_price: 25 },
        ],
      },
    },
    note: 'Полный тест схемы: даты в текстовом формате, массив позиций, услуга (delivery fee) с quantity=1.',
  },
  {
    id: 'ex-contact',
    group: 'contact',
    title: 'Императив в тексте',
    prompt: 'Hey, I am Dana Whitfield, senior analyst at Orbital Labs. Give me a call when you get a chance: +1 (415) 555-0132. You can also reach me by email at d.whitfield@orbitallabs.io.',
    mode: 'extract',
    schema_name: 'contact',
    expect: {
      record: {
        first_name: 'Dana',
        last_name: 'Whitfield',
        phone: '+1 (415) 555-0132',
        email: 'd.whitfield@orbitallabs.io',
        company: 'Orbital Labs',
        role: 'senior analyst',
      },
    },
    note: '«Give me a call» читается как действие и раньше вызывало ложный отказ; чинится catch-all триггером. Опциональные поля вытянуты в начало схемы: модель стабильно отбрасывала хвостовые поля записи.',
  },
  {
    id: 'ex-meeting',
    group: 'meeting_request',
    title: 'Встреча из переписки',
    prompt: "Hi Sarah, following up on our chat - let's do the budget review meeting next Thursday October 1st at 10:30 in room B204. Mark Lee and Priya Sharma will join. Block 90 minutes for it. Best, Tom",
    mode: 'extract',
    schema_name: 'meeting_request',
    system_facts: 'date: 2026-09-26 Sat 14:00',
    expect: {
      record: {
        title: 'Budget review meeting',
        date: '2026-10-01',
        start_time: '10:30',
        duration_minutes: 90,
        location: 'room B204',
        attendees: ['Mark Lee', 'Priya Sharma'],
      },
    },
    note: 'next Thursday разрешается через факт date; ранее «Mark Lee» усекался до «Lee».',
  },
  {
    id: 'ex-ticket',
    group: 'support_ticket',
    title: 'Классификация обращения',
    prompt: "Order #55821. The charger I received last week is completely dead - it doesn't work at all and now my phone is drained and I can't even contact you from it. This is the second faulty unit. I need this fixed today. - Ivan Petrov",
    mode: 'extract',
    schema_name: 'support_ticket',
    expect: {
      record: {
        customer_name: 'Ivan Petrov',
        order_id: '55821',
        category: 'product',
        priority: 'high',
      },
    },
    note: 'Неисправное устройство = product, полная неработоспособность = high. Ранее категория ошибочно определялась как other.',
  },
];

export const scenarioById = Object.fromEntries(SCENARIOS.map((s) => [s.id, s]));
