FROM node:22-alpine AS build
WORKDIR /app
COPY front/package.json front/package-lock.json* ./
RUN npm install
COPY front/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY front/templates/default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
